# -*- coding: utf-8 -*-
"""entrega_pi_1_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OU6ZGPpWXHgioJ4XqkVbCjrBpk3-aULT
"""

# Bloco 1: Imports e Configurações
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuração visual
plt.style.use("seaborn-v0_8")
sns.set_palette("pastel")
pd.set_option("display.max_columns", None)

# Bloco 2: Carregar os datasets
players = pd.read_csv("base_players.csv", sep=";")
lojas = pd.read_csv("lojas_valores.csv", sep=";")
transacoes = pd.read_csv("transacoes_cupons.csv", sep=";")
pedestres = pd.read_csv("pedestres_paulista.csv", sep=";")

# Mostrar dimensões
print("Players:", players.shape)
print("Lojas:", lojas.shape)
print("Transações:", transacoes.shape)
print("Pedestres:", pedestres.shape)

# Bloco 3: Verificar qualidade dos dados

def qualidade_dados(df, nome):
    print(f"\nDataset: {nome}")
    print("Dimensões:", df.shape)
    print("\nTipos de dados:")
    print(df.dtypes)
    print("\nValores ausentes:")
    print(df.isnull().sum())
    print("\nDuplicados:", df.duplicated().sum())
    print("="*60)

qualidade_dados(players, "Players")
qualidade_dados(lojas, "Lojas")
qualidade_dados(transacoes, "Transações")
qualidade_dados(pedestres, "Pedestres")

# Bloco 4: Tratamento básico dos dados

# Remover possíveis duplicados
players = players.drop_duplicates()
lojas = lojas.drop_duplicates()
transacoes = transacoes.drop_duplicates()
pedestres = pedestres.drop_duplicates()

# Remover possíveis valores ausentes
players = players.dropna()
lojas = lojas.dropna()
transacoes = transacoes.dropna()
pedestres = pedestres.dropna()

# Bloco 5: Pré-visualização
print("Players:")
display(players.head())

print("Lojas:")
display(lojas.head())

print("Transações:")
display(transacoes.head())

print("Pedestres:")
display(pedestres.head())

# Bloco 6: Estatísticas descritivas
print("Descrição - Players")
display(players.describe(include="all").T)

print("Descrição - Lojas")
display(lojas.describe(include="all").T)

print("Descrição - Transações")
display(transacoes.describe(include="all").T)

print("Descrição - Pedestres")
display(pedestres.describe(include="all").T)

# Bloco 7: KPIs e análises

# KPI 1: Número de clientes únicos
clientes_totais = players.shape[0]

# KPI 2: Número de lojas parceiras
lojas_unicas = transacoes['nome_estabelecimento'].unique()

# KPI 3: Volume total transacionado
volume_total = lojas["valor_compra"].sum()

# KPI 4: Valor médio dos cupons
valor_medio_cupom = lojas["valor_cupom"].mean()

# KPI 5: Ticket médio por compra
ticket_medio = lojas["valor_compra"].mean()

# KPI 6: Número de pedestres únicos
pedestres_unicos = pedestres.shape[0]


print("📌 KPIs para CEO & CFO")
print(f"Clientes únicos: {clientes_totais}")
print(f"Lojas parceiras: {len(lojas_unicas)}")
print(f"Volume total transacionado: R$ {volume_total:,.2f}")
print(f"Valor médio dos cupons: R$ {valor_medio_cupom:,.2f}")
print(f"Ticket médio: R$ {ticket_medio:,.2f}")
print(f"Pedestres únicos registrados: {pedestres_unicos}")


# Visualizações
fig, axs = plt.subplots(1, 2, figsize=(12,5))

# Distribuição de valores de compra
sns.histplot(lojas["valor_compra"], bins=30, ax=axs[0], kde=True)
axs[0].set_title("Distribuição dos Valores de Compra")

# Relação cupom vs compra
sns.scatterplot(data=lojas.sample(5000), x="valor_cupom", y="valor_compra", alpha=0.5, ax=axs[1])
axs[1].set_title("Cupom vs Valor da Compra")

plt.tight_layout()
plt.show()