# -*- coding: utf-8 -*-
"""ENTREGA_2_PI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOLym-mAKyZtikk6lHsnq5V_gkK6TFwq

## Carregue os dados

### Subtarefa:
Carregue os três arquivos CSV (`base_players.csv`, `lojas_valores.csv` e `transacoes.csv`) nos DataFrames do pandas

**Raciocínio**:
Carregue os três arquivos CSV nos DataFrames do pandas conforme as instruções.
"""

import pandas as pd

df_base_jogadores = pd.read_csv('/content/base_players.csv', sep=';')
df_lojas_valores = pd.read_csv('/content/lojas_valores.csv', sep=';')
df_transacoes = pd.read_csv('/content/transacoes_cupons.csv', sep=';')

"""## Limpe/uniformize os dados

### Subtarefa:
Resolva quaisquer inconsistências, valores ausentes ou tipos de dados incorretos em cada DataFrame. Isso pode envolver a conversão de tipos de dados, o tratamento de valores ausentes e a padronização de dados de texto.

**Raciocínio**:
Inspecione os dataframes para compreender sua estrutura e identificar problemas iniciais de dados.
"""

print("Informações de df_base_jogadores:")
df_base_jogadores.info()
print("\nCabeçalho de df_base_jogadores:")
display(df_base_jogadores.head())

print("\nInformações de df_lojas_valores:")
df_lojas_valores.info()
print("\nCabeçalho de df_lojas_valores:")
display(df_lojas_valores.head())

print("\nInformações de df_transacoes:")
df_transacoes.info()
print("\nCabeçalho de df_transacoes:")
display(df_transacoes.head())

"""**Raciocínio**:
Verifique se há valores ausentes em cada dataframe.
"""

print("Valores ausentes em df_base_jogadores:")
print(df_base_jogadores.isnull().sum())

print("\nValores ausentes em df_lojas_valores:")
print(df_lojas_valores.isnull().sum())

print("\nValores ausentes em df_transacoes:")
print(df_transacoes.isnull().sum())

"""**Raciocínio**:
Lide com valores ausentes, converta tipos de dados e padronize dados de texto nos dataframes com base nos problemas identificados.
"""

# Tratando valores ausentes em df_base_jogadores: Preencher locais de trabalho e escola ausentes com 'Não Informado'
df_base_jogadores[['cidade_trabalho', 'bairro_trabalho', 'cidade_escola', 'bairro_escola']] = df_base_jogadores[['cidade_trabalho', 'bairro_trabalho', 'cidade_escola', 'bairro_escola']].fillna('Não Informado')

# Tratando valores ausentes em df_transacoes: Preencher produto ausente com 'Não Informado'
df_transacoes['produto'] = df_transacoes['produto'].fillna('Não Informado')

# Converter 'data_nascimento' em df_base_jogadores para objetos datetime
df_base_jogadores['data_nascimento'] = pd.to_datetime(df_base_jogadores['data_nascimento'], format='%d/%m/%Y')

# Converter 'data_captura' em df_lojas_valores para objetos datetime
df_lojas_valores['data_captura'] = pd.to_datetime(df_lojas_valores['data_captura'], format='%d/%m/%Y')

# Converter 'data' em df_transacoes para objetos datetime
df_transacoes['data'] = pd.to_datetime(df_transacoes['data'], format='%d/%m/%Y')

# Converter latitude e longitude em df_lojas_valores para numérico, forçando erros
df_lojas_valores['latitude'] = df_lojas_valores['latitude'].astype(str).str.replace('.', '', regex=False).str.replace(',', '.', regex=False)
df_lojas_valores['longitude'] = df_lojas_valores['longitude'].astype(str).str.replace('.', '', regex=False).str.replace(',', '.', regex=False)
df_lojas_valores['latitude'] = pd.to_numeric(df_lojas_valores['latitude'], errors='coerce')
df_lojas_valores['longitude'] = pd.to_numeric(df_lojas_valores['longitude'], errors='coerce')

# Padronizar colunas de texto convertendo para minúsculas e removendo espaços em branco em df_base_jogadores
for col in ['celular', 'sexo', 'cidade_residencial', 'bairro_residencial', 'cidade_trabalho', 'bairro_trabalho', 'cidade_escola', 'bairro_escola', 'categoria_frequentada']:
    df_base_jogadores[col] = df_base_jogadores[col].astype(str).str.lower().str.strip()

# Padronizar colunas de texto convertendo para minúsculas e removendo espaços em branco em df_lojas_valores
for col in ['numero_celular', 'tipo_cupom', 'tipo_loja', 'local_captura', 'nome_loja', 'endereco_loja']:
    df_lojas_valores[col] = df_lojas_valores[col].astype(str).str.lower().str.strip()

# Padronizar colunas de texto convertendo para minúsculas e removendo espaços em branco em df_transacoes
for col in ['celular', 'nome_estabelecimento', 'bairro_estabelecimento', 'categoria_estabelecimento', 'id_campanha', 'id_cupom', 'tipo_cupom', 'produto']:
    df_transacoes[col] = df_transacoes[col].astype(str).str.lower().str.strip()

# Exibir informações e cabeçalho dos dataframes limpos para verificar as alterações
print("Informações de df_base_jogadores limpo:")
df_base_jogadores.info()
print("\nCabeçalho de df_base_jogadores limpo:")
display(df_base_jogadores.head())

print("\nInformações de df_lojas_valores limpo:")
df_lojas_valores.info()
print("\nCabeçalho de df_lojas_valores limpo:")
display(df_lojas_valores.head())

print("\nInformações de df_transacoes limpo:")
df_transacoes.info()
print("\nCabeçalho de df_transacoes limpo:")
display(df_transacoes.head())

"""## Deriva dados

### Subtarefa:
Crie novos recursos ou colunas que possam ser úteis para análise, como combinar colunas de data e hora, calcular durações ou extrair partes de colunas existentes.

**Raciocínio**:
Combine as colunas 'data' e 'hora' no DataFrame `transacoes_df` em uma nova coluna de data e hora chamada 'data_hora', calcule a duração entre 'data_captura' em `lojas_valores_df` e a data atual, extraia o dia da semana e a hora das colunas relevantes em `transacoes_df`.
"""

from datetime import datetime

# 1. Combinar 'data' e 'hora' em df_transacoes
df_transacoes['data_hora'] = pd.to_datetime(df_transacoes['data'].astype(str) + ' ' + df_transacoes['hora'].astype(str))

# 2. Calcular duração em df_lojas_valores
data_atual = datetime.now()
df_lojas_valores['dias_desde_captura'] = (data_atual - df_lojas_valores['data_captura']).dt.days

# 3. Extrair dia da semana de 'data' em df_transacoes
df_transacoes['dia_semana'] = df_transacoes['data'].dt.day_name()

# 4. Extrair hora de 'data_hora' em df_transacoes
df_transacoes['hora_transacao'] = df_transacoes['data_hora'].dt.hour

# Exibir os dataframes atualizados para verificar as novas colunas
print("\nCabeçalho de df_transacoes atualizado:")
display(df_transacoes.head())

print("\nCabeçalho de df_lojas_valores atualizado:")
display(df_lojas_valores.head())

"""# Tarefa
Prepare os dados dos arquivos "base_players.csv", "lojas_valores.csv" e "transacoes.csv", limpando, uniformizando, derivando, integrando e formatando-os. Use sep=";" para ler os CSVs.

## Carregar os dados

### Subtarefa:
Carregue os três arquivos CSV (`base_players.csv`, `lojas_valores.csv` e `transacoes.csv`) em DataFrames pandas, usando ponto e vírgula (`;`) como separador.

**Justificativa**:
Carregue os três arquivos CSV em DataFrames pandas conforme instruído.

## Limpar/uniformizar os dados

### Subtarefa:
Aborde quaisquer inconsistências, valores ausentes ou tipos de dados incorretos em cada DataFrame. Isso pode envolver a conversão de tipos de dados, o tratamento de valores ausentes e a padronização de dados de texto.

**Justificativa**:
Inspecione os dataframes para entender sua estrutura e identificar problemas iniciais de dados.

**Justificativa**:
Verifique se há valores ausentes em cada dataframe.

**Justificativa**:
Trate valores ausentes, converta tipos de dados e padronize dados de texto nos dataframes com base nos problemas identificados.

## Derivar dados

### Subtarefa:
Crie novas características ou colunas que possam ser úteis para análise, como combinar colunas de data e hora, calcular durações ou extrair partes de colunas existentes.

**Justificativa**:
Combine as colunas 'data' e 'hora' no DataFrame `df_transacoes` em uma nova coluna datetime chamada 'data_hora', calcule a duração entre 'data_captura' em `df_lojas_valores` e a data atual, extraia o dia da semana e a hora das colunas relevantes em `df_transacoes`.

## Integrar os dados

### Subtarefa:
Mescle ou combine os DataFrames com base em colunas comuns (por exemplo, `celular` ou `numero_celular`). Determine o tipo apropriado de mesclagem (por exemplo, inner, outer, left, right) com base nos objetivos da análise.

**Justificativa**:
Mescle os três dataframes com base em colunas comuns para integrar os dados. Uma mesclagem à esquerda é apropriada de df_base_jogadores para df_transacoes para manter todas as informações do jogador, e depois outra mesclagem à esquerda para incluir informações relevantes de loja e valor.

## Formatar os dados

### Subtarefa:
Garanta que o DataFrame integrado final esteja em um formato adequado para análise, o que pode incluir renomear colunas, reordenar colunas e garantir tipos de dados consistentes.

**Justificativa**:
Renomeie, reordene e descarte colunas no df_mesclado para clareza e prontidão para análise, em seguida, exiba o cabeçalho e as informações.

## Resumo:

### Principais Descobertas da Análise de Dados

*   Valores ausentes nas colunas de local de trabalho e escola em `df_base_jogadores` e na coluna `produto` em `df_transacoes` foram identificados e preenchidos com 'Não Informado'.
*   As colunas de data (`data_nascimento`, `data_captura`, `data`) nos três dataframes foram convertidas com sucesso para objetos datetime.
*   As colunas de latitude e longitude em `df_lojas_valores` foram limpas e convertidas para um formato numérico.
*   As colunas de texto em todos os dataframes foram padronizadas, convertendo-as para minúsculas e removendo espaços em branco no início/fim.
*   Novas características, incluindo uma coluna combinada de data e hora (`data_hora`), duração desde a captura de dados (`dias_desde_captura`), dia da semana (`dia_semana`) e hora da transação (`hora_transacao`), foram derivadas com sucesso.
*   Os três dataframes foram integrados com sucesso em um único `df_mesclado` usando junções à esquerda com base em `celular` e `numero_celular`.
*   As colunas com sufixos da mesclagem foram renomeadas para serem mais descritivas (por exemplo, `tipo_cupom_transacao`, `tipo_cupom_loja`), e uma coluna redundante (`numero_celular`) foi descartada.
*   As colunas no `df_mesclado` final foram reordenadas em uma sequência lógica para análise.

### Insights ou Próximos Passos

*   O `df_mesclado` integrado e formatado está agora pronto para análise exploratória de dados para descobrir padrões e relacionamentos entre a demografia dos jogadores, o comportamento das transações e as informações da loja.
*   Análises adicionais podem envolver o cálculo de métricas importantes, como valor médio de transação por jogador, frequência de transações ou análise geográfica das localizações de jogadores e lojas.

## Integre os dados

### Subtarefa:
Mesclar ou combinar os DataFrames com base em colunas comuns (por exemplo, `celular` ou `numero_celular`). Determine o tipo apropriado de mesclagem (por exemplo, interna, externa, esquerda, direita) com base nos objetivos da análise.

**Raciocínio**:
Mesclar os três dataframes com base em colunas comuns para integrar os dados. Uma mesclagem à esquerda é apropriada de base_players_df para transacoes_df para manter todas as informações do jogador e, em seguida, outra mesclagem à esquerda para incluir informações relevantes de armazenamento e valor.
"""

# Mesclar df_base_jogadores e df_transacoes em 'celular'
df_mesclado = pd.merge(df_base_jogadores, df_transacoes, on='celular', how='left')

# Mesclar o resultado com df_lojas_valores em 'celular' e 'numero_celular'
df_mesclado = pd.merge(df_mesclado, df_lojas_valores, left_on='celular', right_on='numero_celular', how='left')

# Exibir cabeçalho e informações do dataframe mesclado
print("Cabeçalho do DataFrame Mesclado:")
display(df_mesclado.head())
print("\nInformações do DataFrame Mesclado:")
df_mesclado.info()

"""## Formate os dados

### Subtarefa:
Certifique-se de que o DataFrame final integrado esteja em um formato adequado para análise, o que pode incluir renomear colunas, reordenar colunas e garantir tipos de dados consistentes.

**Raciocínio**:
Renomeie, reordene e elimine colunas no merged_df para maior clareza e preparação para análise e, em seguida, exiba o cabeçalho e as informações.
"""

# 1. Identificar e renomear colunas com sufixos
df_mesclado = df_mesclado.rename(columns={
    'tipo_cupom_x': 'tipo_cupom_transacao',
    'valor_cupom_x': 'valor_cupom_transacao',
    'tipo_cupom_y': 'tipo_cupom_loja',
    'valor_cupom_y': 'valor_cupom_loja',
    'celular_y': 'celular_transacao' # Esta coluna parece redundante após a mesclagem, será descartada
})

# Descartar a coluna redundante numero_celular de df_lojas_valores (agora nomeada celular_transacao após a mesclagem)
df_mesclado = df_mesclado.drop(columns=['numero_celular'])


# 2. Reordenar colunas
# Definir uma ordem lógica para as colunas
ordem_colunas = [
    'celular',
    'data_nascimento',
    'idade',
    'sexo',
    'cidade_residencial',
    'bairro_residencial',
    'cidade_trabalho',
    'bairro_trabalho',
    'cidade_escola',
    'bairro_escola',
    'categoria_frequentada',
    'data',
    'hora',
    'data_hora',
    'dia_semana',
    'hora_transacao',
    'nome_estabelecimento',
    'bairro_estabelecimento',
    'categoria_estabelecimento',
    'tipo_cupom_transacao',
    'valor_cupom_transacao',
    'repasse_picmoney',
    'id_campanha',
    'id_cupom',
    'tipo_cupom_loja',
    'tipo_loja',
    'local_captura',
    'nome_loja',
    'endereco_loja',
    'valor_compra',
    'valor_cupom_loja',
    'dias_desde_captura',
    'latitude',
    'longitude'
]

# Reindexar o DataFrame com a nova ordem das colunas
df_mesclado = df_mesclado.reindex(columns=ordem_colunas)

# 3. Revisar e garantir tipos de dados consistentes (já tratados na limpeza, mas verificar novamente)
# As etapas de limpeza anteriores já converteram colunas de data para datetime e colunas numéricas para numérico.
# Podemos verificar novamente os dtypes aqui, se necessário, mas com base nas saídas info() anteriores, eles devem estar corretos.
# Por exemplo, verificar colunas datetime:
# print(df_mesclado[['data_nascimento', 'data', 'data_hora']].dtypes)
# Verificar colunas numéricas:
# print(df_mesclado[['idade', 'valor_cupom_transacao', 'repasse_picmoney', 'valor_compra', 'valor_cupom_loja', 'dias_desde_captura', 'latitude', 'longitude']].dtypes)


# 5. Exibir o cabeçalho e as informações do DataFrame df_mesclado formatado
print("Cabeçalho do DataFrame Mesclado Formatado:")
display(df_mesclado.head())
print("\nInformações do DataFrame Mesclado Formatado:")
df_mesclado.info()

"""## Resumo:

### Principais conclusões da análise de dados

* Valores faltantes nas colunas de localização trabalho e escola em `base_players_df` e na coluna `produto` em `transacoes_df` foram identificados e preenchidos com 'Não Informado'.
* Colunas de data (`data_nascimento`, `data_captura`, `data`) em todos os três dataframes foram convertidas com sucesso em objetos datetime.
* As colunas de latitude e longitude em `lojas_valores_df` foram limpas e convertidas para formato numérico.
* As colunas de texto em todos os dataframes foram padronizadas, convertendo-as em letras minúsculas e removendo os espaços em branco iniciais/finais.
* Novos recursos incluindo coluna combinada de data e hora (`data_hora`), duração desde a captura de dados (`dias_desde_captura`), dia da semana (`dia_semana`) e hora da transação (`hora_transacao`) foram derivados com sucesso.
* Os três dataframes foram integrados com sucesso em um único `merged_df` usando left joins baseados em `celular` e `numero_celular`.
* Colunas com sufixos provenientes da mesclagem foram renomeadas para serem mais descritivas (por exemplo, `tipo_cupom_transacao`, `tipo_cupom_loja`), e uma coluna redundante (`numero_celular`) foi eliminada.
* As colunas no `merged_df` final foram reordenadas em uma sequência lógica para análise.

### Insights ou próximas etapas

* O `merged_df` integrado e formatado agora está pronto para análise exploratória de dados para descobrir padrões e relacionamentos entre dados demográficos dos jogadores, comportamento de transação e informações de armazenamento.
* Uma análise mais aprofundada poderia envolver o cálculo de métricas importantes, como o valor médio das transações por jogador, a frequência das transações ou a análise geográfica da localização dos jogadores e das lojas.
"""